# Generated by Django 5.2.4 on 2025-07-30 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'CS101 Morning Lecture'", max_length=200)),
                ('session_type', models.CharField(choices=[('single', 'Single Check-In'), ('double', 'Double Check-In')], default='single', max_length=10)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the session URL.', unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session becomes active.')),
                ('end_time', models.DateTimeField(help_text='When the session closes.')),
                ('min_interval', models.PositiveIntegerField(default=5, help_text='Minimum minutes between check-in and check-out (for Double Check-In).')),
                ('checkout_enabled', models.BooleanField(default=False, help_text='Teacher enables this to allow check-outs.')),
                ('wifi_ssid', models.CharField(blank=True, help_text='Wi-Fi Network Name (SSID)', max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, help_text='Wi-Fi Password', max_length=100, null=True)),
                ('roll_number_prefix', models.CharField(blank=True, help_text="e.g., 'C' or 'ENG'", max_length=10, null=True)),
                ('roll_number_letters', models.PositiveIntegerField(blank=True, help_text='Number of alphabet characters after the prefix.', null=True)),
                ('roll_number_digits', models.PositiveIntegerField(blank=True, help_text='Number of digits at the end.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('checkin_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique hidden token for this student's check-in.")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_fingerprint', models.CharField(blank=True, help_text="A hash representing the user's browser configuration.", max_length=255, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'ip_address'), ('session', 'roll_number')},
            },
        ),
    ]
